config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'comments/new'
  get 'comments/create'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  belongs_to :post, foreign_key: 'post_id'

  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end

  private :update_comment_counter
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  belongs_to :post, foreign_key: 'post_id'

  after_save :update_like_counter

  def update_like_counter
    post.increment!(:likes_counter)
  end

  private :update_like_counter
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def last_comments
    comments.where(post_id: self).order(created_at: :desc).limit(5)
  end

  def update_post_counter
    author.increment!(:posts_counter)
  end

  private :update_post_counter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_post
    Post.where(author: self).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmable) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @user = current_user
    @comment = Comment.new(comment_params)
    @comment.author_id = @user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to user_post_path(@user.id, Post.find(params[:post_id]))
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :author, :post)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @author = current_user
    @like = Like.new(params.permit(:author, :post))
    @like.author = @author
    @like.post = @post

    respond_to do |format|
      format.html do
        if @like.save
          redirect_to user_post_url(@author, @post)
        else
          render :new
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @params = params[:user_id]
    @user_by_id = User.find(@params)
    @post_by_user = Post.where(author_id: @params).includes(:author)
    @posts_by_user1 = Post.find_by(author_id: @params)
    @comments_by_user = @posts_by_user1.last_comments.includes(:author)
  end

  def show
    @params_show = params[:id]
    @post_by_user = Post.where(author_id: params[:user_id], id: params[:id])
    @user = current_user
    @comment_by_post = Comment.where(post: @post_by_user).includes(:author)
  end

  def new
    @post_new = Post.new
  end

  def create
    @user = current_user
    @post_new = @user.posts.new(post_params)

    if @post_new.save
      redirect_to user_posts_path(@user.id)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @params = params[:id]
    @user_by_id = User.find(@params)
    @post_by_user = @user_by_id.last_post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_with model: @comment, url: user_post_comments_path, class:"create-comment", method: :post do |form| %>
  <h2>Add a new comment</h2>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
    <%end%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<p class="user-title">Post by user:</p>
<section>
    <article class="user__card">
        <img class="user__img" src = 'https://i.pravatar.cc/150?img=13'>
        <div class="user__information">
            <p class="user__post-counter">Number of post: <%= @user_by_id.posts_counter %></p>
            <h2 class="user__name"><%= @user_by_id.name %></h2>
        <div>
        <p class="user__bio"><%= @user_by_id.bio %></p>
    </article>
    <% @post_by_user.each_with_index do |post, index| %>
    <%= link_to user_post_path(@user_by_id.id, post.id) do %>
        <div class="post__card">
            <h2 class="post__head">Post # <%= index + 1%> by <%= post.author.name %></h2>
            <div class="post__body">
                <p class="post__body-title"><%= post.title %></p>
                <p class="post__body-text"><%= post.text %></p>
            </div>
            <p class="post__footer">
                <span> Comments<%= post.comments_counter %></span> ,
                <span> Likes<%= post.likes_counter %></span>
            </p>
        </div>
    <%end%>  
          <div class="comments">
            <h2 class="comments__topic">Comments:</h2>
            <% @comments_by_user.each do |comment| %>
            <% if post.id === comment.post_id %>
                    <div class="comments__info">
                        <p class="comments__title"><%= comment.author.name %>: </p>
                        <p class="comments__text"><%= comment.text %></p>
                    </div>  
            <% end %> 
            <% end %> 
          </div>

    <% end %>
    <button type="button">Pagination</button>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= @params_create %>
<%= form_with model: @new_post, url: user_posts_path, method: :post, scope: :post do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :text %>
        <%= form.text_field :text %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/posts/show.html.erb
<p class="user-title">Specific Post by user: </p>
<div>
    <% @post_by_user.each_with_index do |post, index| %>
        <div class="post-user">
            <h2 class="post-user__head">Post # <%= index + 1%> by <%= post.author.name %></h2>
            <div class="post-user__body">
                <p class="post-user__body-title"><%= post.title %></p>
                <p class="post-user__body-text"><%= post.text %></p>
            </div>
            <p class="post-user__footer">
                <span> Comments: <%= post.comments_counter %></span> ,
                <span> Likes: <%= post.likes_counter %></span>
            </p>
  
            <%= form_with url: user_post_likes_url(@user, post.id), method: 'post' do |form| %>
             <% form.submit 'Like' %>
            <% end %> 

            <div class= "button-block">
                <button><%= link_to "New Comment", new_user_post_comment_path(@user, post.id) %></button>
            </div>
    
            <div class="comments-user">
                 <h2 class="comments-user__topic">Comments:</h2>
                <% @comment_by_post.each do |comment| %>
                <% if post.id === comment.post_id %>
                <div class="comments-user__info">
                    <p class="comments-user__title"><%= comment.author.name %></p>
                    <p class="comments-user__text"><%= comment.text %></p>
                </div>
            <% end %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<p class="user-title">List of Users:</p>
<% @users.each do |user|%>
<%= link_to user_path(user.id) do %>
<article class="users__container">
<%# <img class="users__image" src=<%= image_path(user.photo) %>
<img class="users__image" src = 'https://i.pravatar.cc/150?img=13'>
<div class="users__info">
    <p class="users__name"><%= user.name %></p>
    <p class="users__post-number">Number of posts: <%= user.posts_counter %></p>
</div>
</article>
<%end%>
<%end%>

app/views/users/show.html.erb
<p class="user-title">User: </p>
<section class="user">
    <article class="user__card">
        <img class="user__img" src = 'https://i.pravatar.cc/150?img=13'>
        <div class="user__information">
            <p class="user__post-counter">Number of post: <%= @user_by_id.posts_counter %></p>
            <h2 class="user__name"><%= @user_by_id.name %></h2>
        <div>
        <p class="user__bio"><%= @user_by_id.bio %></p>
    </article>
    <div class= "button-block">
        <button><%= link_to "New Post", new_user_post_path(@user_by_id.id) %></button>
    </div>
    
    <article class="post">
        <% @post_by_user.each_with_index do |post,index| %>
        <%= link_to user_post_path(@user_by_id.id, post.id) do %>
            <div class="post__card">
                <p class="post__head">Post # <%= index +1 %></p>
                <div class="post__body">
                    <p class="post__body-title"><%= post.title %></p>
                    <p class="post__body-text"><%= post.text %></p>
                </div>
                <p class="post__footer">
                    <span>Comments: <%= post.comments_counter %></span> ,
                    <span>Likes: <%= post.likes_counter %></span>
                </p>
            </div>
        <%end%>
        <% end %>
    </article>
    

     <%= link_to 'See all posts', user_posts_path(@user_by_id.id) if @user_by_id.posts_counter > 3 %>
   
</section>